trigger:
  branches:
    include:
      - Vatsal  # trigger pipeline 

pool:
  vmImage: 'ubuntu-latest'  # ubuntu image for the pipeline

steps:
#  checkout the code from the repository
- task: Checkout@1

# set up Python environment 
- task: UsePythonVersion@0
  inputs:
    addToPath: true  

# install dependencies using pip
- script: |
    python -m venv venv  # create virtual environment
    source venv/bin/activate  # activate virtual environment
    pip install -r requirements.txt  # install dependencies
  displayName: 'Install dependencies'

# run Python tests
- script: |
    source venv/bin/activate  # activate virtual environment
    python -m unittest discover  # run tests
  displayName: 'Run tests'
