trigger:
  branches:
    include:
      - Vatsal  # trigger pipeline when changes are pushed to Vatsal branch

pool:
  vmImage: 'ubuntu-latest'  # using the latest Ubuntu image for the pipeline

steps:
# checkout the code from the repository
- task: Checkout@1

# set up Python environment 
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # specify Python version, e.g., 3.x
    addToPath: true

# install dependencies using pip
- script: |
    python -m venv venv  # create virtual environment
    source venv/bin/activate  # activate virtual environment
    pip install -r Vatsal/requirements.txt  # install dependencies from the Vatsal folder
  displayName: 'Install dependencies'

# run Python tests
- script: |
    source venv/bin/activate  # activate virtual environment
    python -m unittest discover  # run tests
  displayName: 'Run tests'
