

trigger:
- main  # Triggers the pipeline when changes are pushed to the 'main' branch

pool:
  name: SelfHostedPool  

steps:
# Checkout the repository
- checkout: self

# Run a simple script
- script: echo "Hello, self-hosted agent!"
  displayName: 'Run a one-line script'

# Multi-line script for additional tasks
- script: |
    echo "This pipeline is now running on a self-hosted agent."
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml for documentation."
  displayName: 'Run a multi-line script'
