trigger:
- main

pool:
  name: Self-Pool  

stages:
  - stage: checkoutcode
    jobs:
     - job: 'gitcheckoutcode'
       steps:
        - checkout: self
  - stage: Sonarqubeprepare
    jobs:
     - job: 'Sonarqubeanalysis'
       steps:
         - task: SonarQubePrepare@7
           inputs:
             SonarQube: 'SonarQubeAzureSC'
             scannerMode: 'other'
             projectKey: 'TestYAMLSonarQubeKey'
             projectName: 'TestYAMLSonarQubeName'
             
  - stage: mavenbuild
    jobs:
    - job: 'buildANDscancode'
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean install sonar: sonar'
          publishJUnitResults: true
          javaHomeoption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          codeCoverageToolOption: 'JaCoCo'







   


