name: Codacy Analysis

on:
  push:
    branches:
      - main  # Adjust to your branch if needed
  pull_request:
    branches:
      - main

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Codacy
        uses: codacy/codacy-analysis-cli-action@v2  # Update to the latest stable version
        with:
          token: ${{ secrets.yo5swd8ekab7hcucG49P }}  # Uses the token from GitHub Secrets
